// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBualXBk7M7hVv8xweq7H1pASvCW733qe0',
    appId: '1:211403058336:web:fc8004830883b57c8fedc5',
    messagingSenderId: '211403058336',
    projectId: 'toster-ea3a1',
    authDomain: 'toster-ea3a1.firebaseapp.com',
    storageBucket: 'toster-ea3a1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm4p6CUsysTxMtCbvo7zjvODpoJXPufQA',
    appId: '1:211403058336:android:1b72210bf061d6a78fedc5',
    messagingSenderId: '211403058336',
    projectId: 'toster-ea3a1',
    storageBucket: 'toster-ea3a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj6hl6ENXK2b1rfd5YDJ1ZMTzXSIZznfM',
    appId: '1:211403058336:ios:40cb28265b85ba348fedc5',
    messagingSenderId: '211403058336',
    projectId: 'toster-ea3a1',
    storageBucket: 'toster-ea3a1.appspot.com',
    iosClientId: '211403058336-p7es4mbm72344nius50ifmdii7eng9vg.apps.googleusercontent.com',
    iosBundleId: 'com.example.toster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj6hl6ENXK2b1rfd5YDJ1ZMTzXSIZznfM',
    appId: '1:211403058336:ios:40cb28265b85ba348fedc5',
    messagingSenderId: '211403058336',
    projectId: 'toster-ea3a1',
    storageBucket: 'toster-ea3a1.appspot.com',
    iosClientId: '211403058336-p7es4mbm72344nius50ifmdii7eng9vg.apps.googleusercontent.com',
    iosBundleId: 'com.example.toster',
  );
}
